env_file: .env.test

services:
  postgres-test:
    image: postgres:15
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT_INTERNAL:-5432}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT_INTERNAL:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      APP_PORT: ${APP_PORT}
    depends_on:
      - postgres-test
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - ./:/app
    command: >
      sh -c "
        npx typeorm-ts-node-commonjs migration:run -d src/database/data-source.ts &&
        npm run test:integration
      "

volumes:
  pgdata:
